### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ilikeokoge** [kchengiva/Shift-GCN#10]
Hi, thanks for a great codebase!

I tried `python main.py --config ./config/nturgbd-cross-view/train_joint.yaml`
but I encountered "Segmentation fault (core dumped)" on epoch 1.

Do you have any idea?

**Comment by klong121** [comment]
Thanks for your interest. It seems to be an environmental problem in the cuda extension. Because the error does not occur in my environment (python3.6/pytorch0.4.1/cuda9.0/g++5.4.0), it is hard for me to provide advice. You can refer to my environment, or try the environment discussed [here](https://github.com/kchengiva/Shift-GCN/issues/1), or try [docker](https://github.com/kchengiva/Shift-GCN/issues/1#issuecomment-671346073).

**Comment by kchengiva** [comment]
Thanks for your interest. It seems to be an environmental problem when you compile the cuda extension. Because the error does not occur in my environment (python3.6/pytorch0.4.1/cuda9.0/g++5.4.0), it is hard for me to provide advice. You can refer to my environment, or try the environment discussed [here](https://github.com/kchengiva/Shift-GCN/issues/1), or try [docker](https://github.com/kchengiva/Shift-GCN/issues/1#issuecomment-671346073).

**Comment by ilikeokoge** [comment]
Thanks for your advise!

I checked my environment and I understand  that I installed python3.6, pytorch0.4.1 and cuda9.0 but I do not know  g++5.4.0.
How do you check and install?

**Comment by kchengiva** [comment]
Please refer to [here](https://arstechnica.com/civis/viewtopic.php?t=736078). 
Note that if you change g++ version, you may need to reinstall pytorch. Please refer to [here](https://github.com/kchengiva/Shift-GCN/issues/2).
You can also try [docker](https://github.com/kchengiva/Shift-GCN/issues/1#issuecomment-671346073).
