### ISSUE TITLE
undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs

### ISSUE THREAD

**Issue by LaurisZhu** [kchengiva/Shift-GCN#2]
hello, i run the code `bash run.sh` with the environment of pytorch0.4.1/cuda9.0/g++ 5.5，but got the ImportError.
Is there any problem with my environment?

> Installed /home/tjl1/anaconda3/envs/pytorch0.4/lib/python3.7/site-packages/shift_cuda_linear_cpp-0.0.0-py3.7-linux-x86_64.egg
Processing dependencies for shift-cuda-linear-cpp==0.0.0
Finished processing dependencies for shift-cuda-linear-cpp==0.0.0
Traceback (most recent call latt):
	File "demo.py", line 10, in <module>
		from cuda.shift import ShiftFunction, Shift
	FIle "/home/tjl1/zlw/Shift-GCN-master/model/Temporal_shift/cuda/shift.py", lin 5, in <module>
		import shift_cuda
ImportError: /home/tjl1/anaconda3/envs/pytorch0.4/lib/python3.7/site-packages/shift_cuda_linear_cpp-0.0.0-py3.7-linux-x86_64.egg/shift_cuda.cpython-37m-x86_64-linux-gnu.so:
 undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs

**Comment by kchengiva** [comment]
Hello. The error `undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs` also occurs in some other cuda extension programs, such as [mmdetection](https://github.com/open-mmlab/mmdetection/issues/48), [flownet](https://github.com/NVIDIA/flownet2-pytorch/issues/80), and [pytorch_geometric](https://github.com/rusty1s/pytorch_geometric/issues/33). You can refer to these discussions, which may solve your problem @LaurisZhu .
In these discussion, it seems the problem is caused by the compiling environment and runtime environment are not the same. Some people say that re-installing pytorch and torchvision can fix the error.

**Comment by LaurisZhu** [comment]
Thanks for your help. I reinstall the pytorch with the command `conda install pytorch=0.4 torchvision -c pytorch` and the error was gone.
