### ISSUE TITLE
Evaluation Benchmark for NTURGB-d 120

### ISSUE THREAD

**Issue by vivek87799** [kchengiva/Shift-GCN#8]
Dear,
Once again thank you very much for your work.

My apologies for the basic question.
- In general we have a split of training/validation and test on the dataset(ds). validation ds is used for fine tuning the hyper-parameters and the final accuracy is on the test ds
- In case of NTURGB-d the authors suggests two benchmarks xsub and xview

**Question**
1) In your work I observed that the data is split into train and validation. So do you use validation for both fine tuning the hyper-parameters and evaluation ? 
2) In case of x-view benchmark as we are using 3d skeletons wont it be the same when observed from different views, also as the skeleton coordinates are normalised ? (Please correct me if I am wrong)

(I have also observed the same in the previous GCN papers for action recognition)

Thank you

**Comment by kchengiva** [comment]
Thanks for your question. 
In our paper, we use NTU-Xview task to find the appropriate hyper-parameters. This process also exists in many previous works. After finding appropriate hyper-parameters, we do not change hyper-parameters when training on NTU-Xsub task, NTU120-Xsetup task, NTU120-Xsub task and NW-UCLA task, which shows the generalization of hyper-parameters. 
Skeletons coordinate normalisation is commonly used in many previous works. Although skeleton coordinates are normalised, there still be differences between different views because of occlusion and noise. If the normalised 3d skeletons of different views are exactly the same, the accuracy of Xview task should by nearly 100%.

**Comment by vivek87799** [comment]
Thank you very much for the detailed explanation.
